security:
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  role_hierarchy:
    ROLE_ADMIN: [ROLE_ADMIN_COMMENT, ROLE_ADMIN_ARTICLE, ROLE_ALLOWED_TO_SWITCH]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      switch_user: true

      guard:
          authenticators:
              - App\Security\LoginFormAuthenticator
              - App\Security\ApiTokenAuthenticator
          entry_point: App\Security\LoginFormAuthenticator

      logout:
        path: app_logout

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 2592000
  access_control:
#    - { path: ^/admin, roles: ROLE_ADMIN }
#    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/change-password, roles: IS_AUTHENTICATED_FULLY }
#    - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }